export const stores: Store[] = [
  {
    slug: "noon",
    name: "نون",
    en: "noon",
    mono: "n",
    color: "#f2c200",
    fg: "#241a00",
    url: "https://www.noon.com/saudi-ar/",
    affiliate_url: "https://s.noon.com/MzbacIaolAQ",
    tagline: "كل اللي تحتاجه، بمكان واحد",
    desc: "منصة التسوق الأشهر في السعودية — إلكترونيات، أزياء، بقالة، جمال وأكثر، مع توصيل سريع داخل جميع المدن.",
    rating: 4.6,
    reviews: 3214,
    cats: ["electronics", "home", "beauty", "fashion", "kids"],
    updatedH: 2,
    featured: true,
  },
  {
    slug: "amazon", name: "أمازون السعودية", en: "Amazon.sa", mono: "a", color: "#232f3e", fg: "#ffffff",
    url: "https://www.amazon.sa/", tagline: "تشكيلة عالمية بأسعار محلية",
    desc: "ملايين المنتجات من أمازون العالمية مع شحن سريع وبرنامج برايم وإرجاع سهل داخل السعودية.",
    rating: 4.7, reviews: 5402, cats: ["electronics", "home", "kids", "health"], updatedH: 3, featured: true,
  },
  {
    slug: "namshi", name: "نمشي", en: "Namshi", mono: "N", color: "#111111", fg: "#ffffff",
    url: "https://sa.namshi.com/", tagline: "الموضة أولاً",
    desc: "وجهة الموضة الأولى في المنطقة — ماركات عالمية وماركات حصرية مع توصيل سريع وإرجاع مجاني.",
    rating: 4.5, reviews: 2187, cats: ["fashion", "sports"], updatedH: 5, featured: true,
  },
  {
    slug: "shein", name: "شي إن", en: "SHEIN", mono: "S", color: "#161616", fg: "#ffffff",
    url: "https://sain-ar.shein.com/", tagline: "أحدث صيحات الموضة بأسعار مميزة",
    desc: "آلاف القطع الجديدة يومياً من الأزياء والإكسسوارات بأسعار منافسة وشحن مباشر للسعودية.",
    rating: 4.3, reviews: 4873, cats: ["fashion", "beauty", "kids"], updatedH: 6,
  },
  {
    slug: "iherb", name: "آي هيرب", en: "iHerb", mono: "i", color: "#4c8c40", fg: "#ffffff",
    url: "https://sa.iherb.com/", tagline: "صحتك من الطبيعة",
    desc: "متجر الصحة الأول عالمياً — فيتامينات، مكملات، منتجات طبيعية وعضوية مع شحن سريع للسعودية.",
    rating: 4.8, reviews: 6931, cats: ["health", "beauty"], updatedH: 1, featured: true,
  },
  {
    slug: "jarir", name: "مكتبة جرير", en: "Jarir", mono: "J", color: "#e2231a", fg: "#ffffff",
    url: "https://www.jarir.com/", tagline: "تقنية وقرطاسية وكتب",
    desc: "الوجهة الأولى للتقنية والقرطاسية والكتب في السعودية — جوالات، لابتوبات، ألعاب ومستلزمات مكتبية.",
    rating: 4.6, reviews: 3058, cats: ["electronics", "home", "kids"], updatedH: 8,
  },
  {
    slug: "extra", name: "إكسترا", en: "eXtra", mono: "X", color: "#0072ce", fg: "#ffffff",
    url: "https://www.extra.com/", tagline: "أجهزة منزلية وإلكترونيات",
    desc: "سلسلة إلكترونيات سعودية رائدة — أجهزة منزلية، شاشات، جوالات مع ضمان وخدمة تركيب.",
    rating: 4.4, reviews: 1930, cats: ["electronics", "home"], updatedH: 10,
  },
  {
    slug: "nike", name: "نايكي", en: "Nike", mono: "N", color: "#0a0a0a", fg: "#ffffff",
    url: "https://www.nike.com/sa/", tagline: "Just Do It",
    desc: "أحذية وملابس رياضية من نايكي — أحدث الإصدارات والتشكيلات الحصرية للسوق السعودي.",
    rating: 4.7, reviews: 1644, cats: ["sports", "fashion"], updatedH: 12,
  },
  {
    slug: "adidas", name: "أديداس", en: "adidas", mono: "A", color: "#242424", fg: "#ffffff",
    url: "https://www.adidas.com.sa/", tagline: "أداء وتصميم كلاسيكي",
    desc: "ملابس وأحذية رياضية من أديداس — أداء عالٍ وتصاميم كلاسيكية مع عضوية adiClub.",
    rating: 4.5, reviews: 1287, cats: ["sports", "fashion"], updatedH: 14,
  },
  {
    slug: "ikea", name: "ايكيا", en: "IKEA", mono: "I", color: "#0058a3", fg: "#ffdb00",
    url: "https://www.ikea.com/sa/ar/", tagline: "حلول ذكية لمنزلك",
    desc: "أثاث وديكور وحلول تخزين بتصميم اسكندنافي وأسعار مناسبة، مع توصيل وتركيب داخل السعودية.",
    rating: 4.5, reviews: 2496, cats: ["home", "kids"], updatedH: 16,
  },
  {
    slug: "careem", name: "كريم", en: "Careem", mono: "C", color: "#29b474", fg: "#ffffff",
    url: "https://www.careem.com/", tagline: "توصيل ومشاوير ودفع",
    desc: "تطبيق المشاوير والتوصيل الرائد — مشاوير، توصيل طعام وبقالة وباقات اشتراك كريم بلس.",
    rating: 4.4, reviews: 3388, cats: ["food"], updatedH: 4, featured: true,
  },
  {
    slug: "hungerstation", name: "هنقرستيشن", en: "HungerStation", mono: "H", color: "#f7941d", fg: "#3d2400",
    url: "https://hungerstation.com/", tagline: "جوعك علينا",
    desc: "منصة توصيل الطعام الأولى سعودياً — مطاعم، مقاهي وبقالة مع عروض يومية على الطلبات.",
    rating: 4.3, reviews: 2719, cats: ["food"], updatedH: 7,
  },
  {
    slug: "almosafer", name: "المسافر", en: "Almosafer", mono: "M", color: "#6e3fa3", fg: "#ffffff",
    url: "https://www.almosafer.com/", tagline: "سفر أسهل وأوفر",
    desc: "منصة سعودية لحجوزات الطيران والفنادق والباقات السياحية بأفضل الأسعار وعروض حصرية.",
    rating: 4.4, reviews: 1512, cats: ["travel"], updatedH: 9,
  },
  {
    slug: "bathbody", name: "باث اند بودي", en: "Bath & Body", mono: "B", color: "#0b5cab", fg: "#ffffff",
    url: "https://www.bathandbodyworks.com.sa/", tagline: "عناية تدوم طويلاً",
    desc: "منتجات العناية بالجسم والعطور المنزلية من باث اند بودي وركس — تشكيلات موسمية وعروض مستمرة.",
    rating: 4.6, reviews: 986, cats: ["beauty"], updatedH: 11,
  },
];
